### ISSUE TITLE
Use from a PHP script: example not working

### ISSUE THREAD

**Issue by beastybeast** [psyon/php-qrcode#3]
$options is not defined in the readme example ;-)

**Comment by beastybeast** [comment]
And if you specify an empty array you get an error:

Undefined array key "s" in /xxx/qrcode.php on line 142

**Comment by psyon** [comment]
$data isn't defined either.  It's not meant to be a complete example.  The two variables used are just showing the argument order of the constructor, and are the same way in the examples of the parent repository of the larger library.  I will fix the undefined array key issue.  I should probably put in some default options that are merged in when creating a new instance, but my intention was not to fix the code from the parent repository, only to slim it down and remove what I did not need.
